### ISSUE TITLE
module.exports.dependencies: gulp is not defined

### ISSUE THREAD

**Issue by vestman** [ethancfchen/gulp-load-all-tasks#1]
First: Finally a task loader that works with Gulp 4, thank you!

However, I just noticed that it throws an error if you try do define a task dependency using `module.exports.dependencies`. 

_gulpfile.js_
```
require('gulp-load-all-tasks')();
```

_gulp-tasks/hello.js_
```
'use strict';

module.exports = function() {
    return new Promise(resolve => {
        console.log('Hello');
        resolve();
    });
};
module.exports.dependencies = gulp.series('world');
```

_gulp-tasks/world.js_
```
'use strict';

module.exports = function() {
    return new Promise(resolve => {
        console.log('World');
        resolve();
    });
};
```

Running `$ gulp hello` throws this error:
```
/tmp-gulp-load-all-tasks/gulp-tasks/hello.js:9
module.exports.dependencies = gulp.parallel('world');
                              ^

ReferenceError: gulp is not defined
    at Object.<anonymous> (/tmp-gulp-load-all-tasks/gulp-tasks/hello.js:9:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadTask (/tmp-gulp-load-all-tasks/node_modules/gulp-load-all-tasks/index.js:30:26)
    at loadTasks (/tmp-gulp-load-all-tasks/node_modules/gulp-load-all-tasks/index.js:59:7)
```

**Comment by mindpixel-labs** [comment]
@vestman Try adding this to the top of your task file in hello.js

```javascript
const gulp = require('gulp');
```

You need to define your dependencies within your task. It won't have access to the global scope.

**Comment by fynncfchen** [comment]
Yes, you need to import `gulp` first.
